# Generated by Django 5.2.1 on 2025-06-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_roadtypeagencymapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
