# Generated by Django 5.2.1 on 2025-06-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_report_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
